version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 200

  - package-ecosystem: npm
    directory: "/functions"
    schedule:
      interval: daily
    open-pull-requests-limit: 200
