# baseurl is updated on deploy
baseurl = "/"
languageCode = "en-us"
title = 'MaxMind'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[menus]
  [[menus.minfraud]]
    name = 'minFraud'
    pageRef = '/minfraud'
    weight = 10
  [[menus.geoip]]
    name = 'GeoIP'
    pageRef = '/geoip'
    weight = 10
  [[menus.general]]
    name = 'MaxMind Server IP Addresses'
    pageRef = '/maxmind-server-ip-addresses'
    weight = 10

[module]
  [[module.mounts]]
    source = "data/mm_ips.json"
    target = "static/maxmind-server-ip-addresses.json"

[outputs]
  home = ["HTML"]
