import { SchemaObject } from 'openapi3-ts';

const Payment: SchemaObject = {
  properties: {
    decline_code: {
      description: 'The decline code as provided by your payment processor. If the transaction was not declined, do not include this field.',
      example: 'card_declined',
      maxLength: 255,
      type: 'string',
    },
    processor: {
      description: 'If your payment processor is missing from this list, please contact [support@maxmind.com}(mailto:support@maxmind.com).',
      enum: [
        'adyen',
        'altapay',
        'amazon_payments',
        'authorizenet',
        'balanced',
        'beanstream',
        'bluepay',
        'braintree',
        'ccnow',
        'chase_paymentech',
        'cielo',
        'collector',
        'compropago',
        'concept_payments',
        'conekta',
        'cuentadigital',
        'dalpay',
        'dibs',
        'digital_river',
        'ebs',
        'ecomm365',
        'elavon',
        'epay',
        'eprocessing_network',
        'eway',
        'first_data',
        'global_payments',
        'hipay',
        'ingenico',
        'internetsecure',
        'intuit_quickbooks_payments',
        'iugu',
        'lemon_pay',
        'mastercard_payment_gateway',
        'mercadopago',
        'merchant_esolutions',
        'mirjeh',
        'mollie',
        'moneris_solutions',
        'nmi',
        'openpaymx',
        'optimal_payments',
        'orangepay',
        'other',
        'pacnet_services',
        'payfast',
        'paygate',
        'payone',
        'paypal',
        'payplus',
        'paystation',
        'paytrace',
        'paytrail',
        'payture',
        'payu',
        'payulatam',
        'pinpayments',
        'princeton_payment_solutions',
        'psigate',
        'qiwi',
        'quickpay',
        'raberil',
        'rede',
        'redpagos',
        'rewardspay',
        'sagepay',
        'simplify_commerce',
        'skrill',
        'smartcoin',
        'sps_decidir',
        'stripe',
        'telerecargas',
        'towah',
        'usa_epay',
        'verepay',
        'vindicia',
        'virtual_card_services',
        'vme',
        'worldpay',
      ],
      example: 'stripe',
      type: 'string',
    },
    was_authorized: {
      description: 'The authorization outcome from the payment processor. If the transaction has not yet been approved or denied, do not include this field.',
      example: 'false,',
      type: 'boolean',
    },
  },
  type: 'object',
};

export default Payment;
