#!/usr/bin/env node

/**
 * Generate static/_headers file from scripts/_headers.config.ts
 *
 * This script converts a structured TypeScript configuration into the
 * Cloudflare Pages _headers format.
 */

import * as fs from 'fs';
import * as path from 'path';

import config from './_headers.config.js';

interface PathConfig {
  pattern: string;
  headers: Record<string, string | Record<string, string | string[]>>;
}

/**
 * Generate _headers file content from config
 */
function generateHeaders(
  config: { paths: PathConfig[] }
): string {
  let output = '';

  // Add warning comment at the top
  output += '# ⚠️  DO NOT EDIT THIS FILE DIRECTLY!\n';
  output += '# This file is automatically generated from scripts/_headers.config.ts\n';
  output += '# To make changes, edit scripts/_headers.config.ts and run: npm run build:headers\n';
  output += '#\n';
  output += '# See README.md for more information\n';
  output += '\n';

  for (const pathConfig of config.paths) {
    // Write path pattern
    output += pathConfig.pattern + '\n';

    // Process CSP first if it exists
    if (pathConfig.headers['Content-Security-Policy']) {
      const csp = pathConfig.headers['Content-Security-Policy'] as Record<
        string,
        string | string[]
      >;
      const directives: string[] = [];

      for (const [
        directive,
        sources,
      ] of Object.entries(csp)) {
        if (Array.isArray(sources)) {
          directives.push(`${directive} ${sources.join(' ')}`);
        } else {
          directives.push(`${directive} ${sources}`);
        }
      }

      output += `  Content-Security-Policy: ${directives.join('; ')}\n`;
    }

    // Process other headers
    for (const [
      header,
      value,
    ] of Object.entries(pathConfig.headers)) {
      if (header === 'Content-Security-Policy') continue;

      output += `  ${header}: ${value}\n`;
    }
  }

  return output;
}

// Main execution
try {
  const outputPath = path.join(process.cwd(), 'static', '_headers');

  // Generate headers file
  const headersContent = generateHeaders(config);

  // Write output file
  fs.writeFileSync(outputPath, headersContent);

  console.log('✅ Generated static/_headers from scripts/_headers.config.ts');
} catch (error) {
  console.error(
    'Error generating headers file:',
    error instanceof Error ? error.message : String(error)
  );
  process.exit(1);
}
