name: Hugo

on:
  push:
  pull_request:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # 3.0.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Install ubi, htmlq and html2markdown
        uses: oalders/install-ubi-action@27bdce90e4b0e0a6c26023610ab03e375c6ed3e3 # 0.0.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projects: |
            JohannesKaufmann/html-to-markdown --exe html2markdown
            mgdm/htmlq

      - name: Build site
        run: ./build.sh
        env:
          CF_PAGES_URL: /
